name: Validate SQL Queries

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v6

      - name: Check query-examples are up to date
        run: uv run scripts/render.py --check

      - name: Download latest database
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --pattern 'database.zip'
          unzip database.zip

      - name: Validate queries
        run: uv run scripts/validate.py --db database.sqlite3
